--测试表
DROP TABLE IF EXISTS SYS_TEST;
CREATE TABLE SYS_TEST(
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    AGE TINYINT,
    CASH DECIMAL(20, 2),
    UNIQUE_CODE UUID,
    BIRTHDATE DATE,
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);

--user
DROP TABLE IF EXISTS SYS_USER;
CREATE TABLE SYS_USER(
    UNIQUE_CODE UUID PRIMARY KEY,
    NAME VARCHAR(255),
    MOBILE VARCHAR(255),
    EMAIL VARCHAR(255),
    TYPE VARCHAR(20),
    OPENID VARCHAR(255),
    STATUS VARCHAR(20),
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);

-- weixin user info
DROP TABLE IF EXISTS SYS_USERINFO_WX;
CREATE TABLE SYS_USERINFO_WX(
    UNIQUE_CODE UUID PRIMARY KEY,
    OPENID VARCHAR(255),
    NICKNAME VARCHAR(255),
    SEX VARCHAR(20),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    PROVINCE VARCHAR(255),
    LANGUAGE VARCHAR(20),
    HEADIMGURL VARCHAR(1000),
    UNIONID VARCHAR(255),
    GROUPID VARCHAR(255),
    REMARK VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);

--file store mapping
DROP TABLE IF EXISTS SYS_FILE_STORE_MAPPING;
CREATE TABLE SYS_FILE_STORE_MAPPING(
    UNIQUE_CODE UUID PRIMARY KEY,
    NAME VARCHAR(255),
    PATH VARCHAR(255),
    FILE_EXTENSION VARCHAR(20),
    FILE_SIZE LONG,
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);
--日志表：HTTP请求
DROP TABLE IF EXISTS LOG_HTTP;
CREATE TABLE LOG_HTTP(
    ID BIGINT IDENTITY PRIMARY KEY,
    METHOD_NAME VARCHAR(50),
    URI VARCHAR(2500),
    REQUEST VARCHAR(2500),
    RESPONSE VARCHAR(2500),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
); 

--日志表：用户登录记录
DROP TABLE IF EXISTS LOG_VISIT;
CREATE TABLE LOG_VISIT(
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    REMARK VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
); 

--日志表：调用http返回错误消息日志
DROP TABLE IF EXISTS LOG_ERRORABLE;
CREATE TABLE LOG_ERRORABLE(
    ID BIGINT IDENTITY PRIMARY KEY,
    URI VARCHAR(2500),
    ERRORABLE VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
); 

