--user
DROP TABLE IF EXISTS TX_USER;
CREATE TABLE TX_USER(
    UNIQUE_CODE UUID PRIMARY KEY,
    NAME VARCHAR(255),
    MOBILE VARCHAR(255),
    EMAIL VARCHAR(255),
    TYPE VARCHAR(20),
    OPENID VARCHAR(255),
    STATUS VARCHAR(20),
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);

-- weixin user info
DROP TABLE IF EXISTS TX_USERINFO_WX;
CREATE TABLE TX_USERINFO_WX(
    UNIQUE_CODE UUID PRIMARY KEY,
    OPENID VARCHAR(255),
    NICKNAME VARCHAR(255),
    SEX VARCHAR(20),
    CITY VARCHAR(255),
    COUNTRY VARCHAR(255),
    PROVINCE VARCHAR(255),
    LANGUAGE VARCHAR(20),
    HEADIMGURL VARCHAR(1000),
    UNIONID VARCHAR(255),
    GROUPID VARCHAR(255),
    REMARK VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);

--order 
DROP TABLE IF EXISTS TX_ORDER;
CREATE TABLE TX_ORDER(
    UNIQUE_CODE UUID PRIMARY KEY,
    USER_UC UUID,
    SUMMARY VARCHAR(255),
    TOTAL_AMT DECIMAL(20, 2),
    STATUS VARCHAR(20),
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);
--order item
DROP TABLE IF EXISTS TX_ORDER_ITEM;
CREATE TABLE TX_ORDER_ITEM(
    UNIQUE_CODE UUID PRIMARY KEY,
    ORDER_UC UUID,
    PRODUCT_UC UUID,
    PRODUCT_COUNT DECIMAL(20, 2),
    TOTAL_AMT DECIMAL(20, 2),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);

--product
DROP TABLE IF EXISTS TX_PRODUCT;
CREATE TABLE TX_PRODUCT(
    UNIQUE_CODE UUID PRIMARY KEY,
    NAME VARCHAR(255),
    PRICE DECIMAL(20, 2),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);

--product detail
DROP TABLE IF EXISTS TX_PRODUCT_DETAIL;
CREATE TABLE TX_PRODUCT_DETAIL(
    UNIQUE_CODE UUID PRIMARY KEY,
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);


--shopping cart
DROP TABLE IF EXISTS TX_SHOPPING_CART;
CREATE TABLE TX_SHOPPING_CART(
    UNIQUE_CODE UUID PRIMARY KEY,
    USER_UC UUID,
    PRODUCT_UC UUID,
    PRODUCT_COUNT DECIMAL(20, 2),
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);