--user
DROP TABLE IF EXISTS TX_USER;
CREATE TABLE TX_USER(
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    MOBILE VARCHAR(255),
    EMAIL VARCHAR(255),
    TYPE VARCHAR(20),
    OPENID VARCHAR(255),
    UNIQUE_CODE UUID,
    STATUS VARCHAR(20),
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP
);

--order 
DROP TABLE IF EXISTS TX_ORDER;
CREATE TABLE TX_ORDER(
    ID BIGINT IDENTITY PRIMARY KEY,
    USER_ID BIGINT,
    SUMMARY VARCHAR(255),
    TOTAL_AMT DECIMAL(20, 2),
    STATUS VARCHAR(20),
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP
);
--order item
DROP TABLE IF EXISTS TX_ORDER_ITEM;
CREATE TABLE TX_ORDER_ITEM(
    ID BIGINT IDENTITY PRIMARY KEY,
    ORDER_ID BIGINT,
    PRODUCT_ID BIGINT,
    PRODUCT_COUNT DECIMAL(20, 2),
    TOTAL_AMT DECIMAL(20, 2),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP
);

--product
DROP TABLE IF EXISTS TX_PRODUCT;
CREATE TABLE TX_PRODUCT(
    ID BIGINT IDENTITY PRIMARY KEY,
    NAME VARCHAR(255),
    PRICE DECIMAL(20, 2),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP
);

--product detail
DROP TABLE IF EXISTS TX_PRODUCT_DETAIL;
CREATE TABLE TX_PRODUCT_DETAIL(
    ID BIGINT IDENTITY PRIMARY KEY,
    PRODUCT_ID BIGINT,
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP
);