--user
DROP TABLE IF EXISTS TX_USER;
CREATE TABLE TX_USER(
    UNIQUE_CODE UUID PRIMARY KEY,
    NAME VARCHAR(255),
    MOBILE VARCHAR(255),
    EMAIL VARCHAR(255),
    TYPE VARCHAR(20),
    OPENID VARCHAR(255),
    STATUS VARCHAR(20),
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP
);

--order 
DROP TABLE IF EXISTS TX_ORDER;
CREATE TABLE TX_ORDER(
    UNIQUE_CODE UUID PRIMARY KEY,
    USER_UC UUID,
    SUMMARY VARCHAR(255),
    TOTAL_AMT DECIMAL(20, 2),
    STATUS VARCHAR(20),
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP
);
--order item
DROP TABLE IF EXISTS TX_ORDER_ITEM;
CREATE TABLE TX_ORDER_ITEM(
    UNIQUE_CODE UUID PRIMARY KEY,
    ORDER_UC UUID,
    PRODUCT_UC UUID,
    PRODUCT_COUNT DECIMAL(20, 2),
    TOTAL_AMT DECIMAL(20, 2),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP
);

--product
DROP TABLE IF EXISTS TX_PRODUCT;
CREATE TABLE TX_PRODUCT(
    UNIQUE_CODE UUID PRIMARY KEY,
    NAME VARCHAR(255),
    PRICE DECIMAL(20, 2),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP
);

--product detail
DROP TABLE IF EXISTS TX_PRODUCT_DETAIL;
CREATE TABLE TX_PRODUCT_DETAIL(
    UNIQUE_CODE UUID PRIMARY KEY,
    PRODUCT_UC UUID,
    REMARK VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP
);