--cookbook
DROP TABLE IF EXISTS KHH_COOKBOOK;
CREATE TABLE JR_COOKBOOK(
    UNIQUE_CODE UUID PRIMARY KEY,
    NAME VARCHAR(255),
    THUMBNAIL UUID,
    TYPE VARCHAR(20),
    ENABLE BOOLEAN DEFAULT TRUE,
    HEALTHY_RATING INT,
    PRIORITY INT,
    BRIEF VARCHAR(255),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);

--dish
DROP TABLE IF EXISTS JR_DISH;
CREATE TABLE JR_DISH(
    UNIQUE_CODE UUID PRIMARY KEY,
    COOKBOOK_UC UUID,
    BATCH VARCHAR(20),
    CREATOR VARCHAR(255),
    CREATE_TIME TIMESTAMP DEFAULT SYSDATE
);

